### ISSUE TITLE
Celery stops consuming queues

### ISSUE THREAD

**Issue by east** [upTee/upTee#87]
After some hours or normal usage by uptee users, celery simply blocks and queues in rabbitmq are filling up.
```
$ rabbitmqctl list_queues
Listing queues ...
celery  686
celery@upteehost.celery.pidbox  0
celeryev.bc75a72f-4b37-496a-b230-3434095e32d9   0
```

Not reproducible for me since I cannot break stuff like an average user does all the time =)
Also I don't know how to trace back celery/rabbitmq issues

Version:
Django (1.5)
django-celery (3.1.16)
rabbitmq-server-3.4.3

**Comment by SushiTee** [comment]
In the start script could you try to do:

    celery worker -E -l info -Ofair

Please give feedback if it works or not after some time.

**Comment by east** [comment]
Using this command celery only starts 2 (number of cpu core) workers and each of them only can only run one task at the same time. That's why before I used ***--concurrency x*** to increase the number of workers.

Maybe I have some misconfiguration?

**Comment by SushiTee** [comment]
If I remember correctly the server just stoped otherwise. But I'm not sure.

Well with the "Ofair" option you could spawn as many workers as you would need for all servers and there souldn't be any atempts of cerly to try to run multiple tasks for one worker.
If this is a good idea... I don't know but those were my thoughts: :/

Did you try to run the server without the wait?

**Comment by east** [comment]
Hm -Ofair seems not to work for me. It hangs after starting two servers.
But for me it works by removing the pid wait()
> If I remember correctly the server just stoped otherwise. But I'm not sure.

Iirc subprocesses keep running after the parent dies. And since uptee keeps track of the process id I prefer this option.
